.TH printf 3 "31 Mar 2023" "1.0" "_printf Manual"

.SH NAME
_printf \- Custom printf function that prints output format

.SH SYNOPSIS
#include "main.h"

int _printf(const char *format, ...);

int print_char(va_list);
int print_str(va_list);
int print_perc(va_list);
int print_uint(unsigned int n);
int print_int(va_list);
int print_hex(unsigned long int n);
int print_ptr(va_list args);
int print_unsigned(va_list args);
int print_address(va_list args);

.SH DESCRIPTION
The _printf function is a custom implementation of the standard printf function
which prints a formatted string to the standard output stream. It accepts a
format string which can include conversion specifiers and flags that modify
the output. Conversion specifiers are specified using the '%' character and
are followed by a character that specifies the type of output to be printed.

The _printf function uses a table of function pointers to dispatch to the
appropriate conversion function based on the conversion specifier character.
The conversion functions are responsible for parsing the arguments passed to
the _printf function and formatting them into the appropriate output format.

The supported conversion specifiers are:

%c: print a single character
%s: print a null-terminated string
%d, %i: print a signed decimal integer
%%: print a literal percent symbol

.SH FUNCTIONS
The following functions are used in _printf and are defined in func.c:

.IP print_char
int print_char(va_list args);

The print_char function prints a single character to the standard output stream.
It accepts a va_list argument containing the character to be printed.

.IP print_str
int print_str(va_list args);

The print_str function prints a null-terminated string to the standard output
stream. It accepts a va_list argument containing a single argument of type char*.

.IP print_perc
int print_perc(va_list args);

The print_perc function prints a percent symbol to the standard output stream.
It accepts an empty va_list argument and returns 1.

.IP print_int
int print_int(va_list args);

The print_int function prints a signed decimal integer to the standard output
stream. It accepts a va_list argument containing the integer to be printed and
returns the number of characters printed.

.IP print_ptr
int print_ptr(va_list args);

The print_ptr function prints the address of a pointer argument to the standard
output stream. It accepts a va_list argument containing the pointer argument
and returns the number of characters printed.

.SH AUTHORS
Written by Djamaldine Mohamed and Noah Vernhet
